Models/ErrorViewModel.cs
using System;

namespace OrangeOrchard.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MovieGenreViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace OrangeOrchard.Models
{
    public class MovieGenreViewModel
    {
        public List<Tree> trees;
        public SelectList genres;
        public string movieGenre { get; set; }
    }
}

Models/OrangeOrchardContext.cs
using Microsoft.EntityFrameworkCore;

namespace OrangeOrchard.Models
{
    public class OrangeOrchardContext : DbContext
    {
        public OrangeOrchardContext (DbContextOptions<OrangeOrchardContext> options)
            : base(options)
        {
        }

        public DbSet<OrangeOrchard.Models.Tree> Tree { get; set; }
    }
}

Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace OrangeOrchard.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new OrangeOrchardContext(
                serviceProvider.GetRequiredService<DbContextOptions<OrangeOrchardContext>>()))
            {
                // Look for any trees.
                if (context.Tree.Any())
                {
                    return;   // DB has been seeded
                }

                context.Tree.AddRange(
                     new Tree
                     {
                         Name = "OrangeTree1",
                         //YearPlanted = DateTime.Parse("1989"),
                         Age = 28,
                         //NumOranges = 20
                         Genre = "one",
                     },
                     new Tree
                     {
                         Name = "OrangeTree2",
                         //YearPlanted = DateTime.Parse("1989"),
                         Age = 28,
                         //NumOranges = 20
                         Genre = "two",
                     },
                    new Tree
                     {
                         Name = "OrangeTree3",
                         //YearPlanted = DateTime.Parse("1989"),
                         Age = 28,
                         //NumOranges = 20
                         Genre = "three",
                     }
                );
                context.SaveChanges();
            }
        }
    }
}

Models/Tree.cs
using System;
using System.ComponentModel.DataAnnotations;
using static System.Math;

namespace OrangeOrchard.Models
{
    public class Tree
    {
        public int ID { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Name { get; set; }

        /*possibly ditch in favour of just age
        [Display(Name = "Year Planted")]
        [DataType(DataType.Year)]
        public DateTime YearPlanted { get; set; }*/

        [Range(1, 150)]
        public int Age { get; set; }
        //uses year planted and ?current year?
        
        /*Create oranges class
        [Display(Name = "Number of Oranges")]
        [Range(1, 100)]
        public int NumOranges { get; set; }*/
        public string Genre {get; set;}
    }
}

Controllers/TreesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OrangeOrchard.Models;

namespace OrangeOrchard.Controllers
{
    public class TreesController : Controller
    {
        private readonly OrangeOrchardContext _context;

        public TreesController(OrangeOrchardContext context)
        {
            _context = context;
        }

        // GET: Trees
        // Requires using Microsoft.AspNetCore.Mvc.Rendering;
        public async Task<IActionResult> Index(string movieGenre, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Tree
                                            orderby m.Genre
                                            select m.Genre;

            var trees = from m in _context.Tree
                        select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                trees = trees.Where(s => s.Name.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(movieGenre))
            {
                trees = trees.Where(x => x.Genre == movieGenre);
            }

            var movieGenreVM = new MovieGenreViewModel();
            movieGenreVM.genres = new SelectList(await genreQuery.Distinct().ToListAsync());
            movieGenreVM.trees = await trees.ToListAsync();

            return View(movieGenreVM);
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: Trees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tree = await _context.Tree
                .SingleOrDefaultAsync(m => m.ID == id);
            if (tree == null)
            {
                return NotFound();
            }

            return View(tree);
        }

        // GET: Trees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Age")] Tree tree)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tree);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tree);
        }

        /* CURRENTLY NOT IN USE/ GET: Trees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var  = await _context.Tree.SingleOrDefaultAsync(m => m.ID == id);
            if ( == null)
            {
                return NotFound();
            }
            return View();
        }

        // POST: Trees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Age,Height,NumOranges")] Tree )
        {
            if (id != .ID)
            {
                return NotFound();
            }
            //verifies data can modify  object
            if (ModelState.IsValid)
            {
                try
                {
                    //saves edited  data to database
                    _context.Update();
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //returns to index page
                return RedirectToAction(nameof(Index));
            }
            return View();
        }*/

        // GET: Trees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tree = await _context.Tree
                .SingleOrDefaultAsync(m => m.ID == id);
            if (tree == null)
            {
                return NotFound();
            }

            return View(tree);
        }

        // POST: Trees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tree = await _context.Tree.SingleOrDefaultAsync(m => m.ID == id);
            _context.Tree.Remove(tree);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Tree.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tree App</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Trees" asp-action="Index" class="navbar-brand">OrangeOrchard</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Trees" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Trees" asp-action="Create">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - OrangeOrchard</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Trees/Create.cshtml
@model OrangeOrchard.Models.Tree

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Tree</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Trees/Delete.cshtml
@model OrangeOrchard.Models.Tree

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tree</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Trees/Details.cshtml
@model OrangeOrchard.Models.Tree

@{
    ViewData["Title"] = "Details";
}

@section Scripts
{
    <script type="text/javascript" src="@Url.Content("https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/examples/vendor/aframe/build/aframe.min.js")"></script>
    <script type="text/javascript" src="Url.Content("https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js")"></script>

}
<div style='margin : 0px overflow: hidden;'>
    <h2>Details</h2>

    <script>
        AFRAME.registerComponent('scale-on-mouseenter', {
        schema: {
            to: {default: '0.5'}
        },
        init: function () {
            var data = this.data;
            this.el.addEventListener('mouseenter', function () {
            this.setAttribute('radius', data.to);
            });
        }
        });
    </script>

    <!-- create 3d scene -->
    <a-scene embdedded arjs='trackingMethod: best;'>
        <a-assets>
        <a-asset-item id="tree-obj" src="https://ucarecdn.com/f42822e6-aa9d-4f7a-8ab7-f7bc3670e68c/"></a-asset-item>
        <a-asset-item id="tree-mtl" src="https://ucarecdn.com/d2a1464a-d738-4ff8-baf8-5378217b3de3/"></a-asset-item>
        </a-assets>
        <!-- ar content goes here -->
        <!-- simple content - simmple sphere added and made it transparent and put it ON TOP of marker-->

        <!-- oranges -->
        <a-sphere position="0.3 -0.5 0" radius="0.1" color="#FF4500" material="opacity: 0.5" scale-on-mouseenter="to: 0"></a-sphere>

        <!--Orange tree -->
        <a-entity scale='0.01 0.01 0.01' rotation='7.7 -180.0 .057' position='-0.06 -0.5 0.2' obj>
        <a-entity obj-model="obj: #tree-obj; mtl: #tree-mtl"></a-entity>
        </a-entity>

        <a-text position="0 0.5 0" value="Hello, World! Please work soon"></a-text>
        <!-- can also do this inline but less performant -->
        <!--a-entity obj-model="obj: url(/path/to/tree.obj); mtl: url(/path/to/tree.mtl)"></a-entity -->

        <!-- add the camera! and tell it what marker you are using (hiro in this case) -->
        <a-marker-camera preset='hiro'></a-marker-camera>
        <a-camera>
        <!-- a-camera-static/ -->
        <a-cursor></a-cursor>
        </a-camera>
    </a-scene>
</div>



<!-- notes for later
@Html.DisplayNameFor(model => model.Name)
@Html.DisplayFor(model => model.Name)
@Html.DisplayNameFor(model => model.ReleaseDate)
@Html.DisplayFor(model => model.ReleaseDate)-->

Views/Trees/Edit.cshtml
@model OrangeOrchard.Models.Tree

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Tree</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Trees/Index.cshtml
@model OrangeOrchard.Models.MovieGenreViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<!-- add search with method get to specify request-->
<form asp-controller="Trees" asp-action="Index" method="get">
    <p>
        <select asp-for="movieGenre" asp-items="Model.genres">
            <option value="">All</option>
        </select>

        Name: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.trees[0].Name)
                </th>
                <!--th>
                    @Html.DisplayNameFor(model => model.trees[0].YearPlanted)
                </th -->
                <th>
                    @Html.DisplayNameFor(model => model.trees[0].Age)
                </th>
                <th>
                    Height
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.trees[0].NumOranges)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.trees)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <!--td>
                    @Html.DisplayFor(modelItem => item.YearlPlanted)
                </td-->
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumOranges)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>